[package]
license = "Apache-2.0"
name = "config"
version.workspace = true
edition.workspace = true
description = "Shared loading for Grow's user and project config files"

[dependencies]
blake3 = { workspace = true }
dunce = { workspace = true }
libc = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shellexpand = "3.1"
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
which = { workspace = true }
tty-utils = { workspace = true }
version = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]

[lints]
workspace = true
